### ISSUE TITLE
TypeError: Cannot read property 'id' of null

### ISSUE THREAD

**Issue by rattrayalex** [filepicker/filepicker-js#21]
Getting the following error via Rollbar:

```
TypeError: Cannot read property 'id' of null
1 File https://api.filepicker.io/v2/filepicker.js line 1 col 3830 in Object.n
2 File https://api.filepicker.io/v2/filepicker.js line 1 col 215 in Object.function.r.isClass.n.(anonymous
3 File https://api.filepicker.io/v2/filepicker.js line 1 col 1115 in i
```

Occurring primarily in Chrome

**Comment by krystiangw** [comment]
@rattrayalex I'm closing it for now but reopen it if you find any further details.

**Comment by ArthurGuy** [comment]
I have been having the same problem for a while now.
Is the a sourcemap for filepicker or an unminified version that I can use to debug this?

**Comment by rattrayalex** [comment]
I think this might be the result of trying to initialize filepicker on a target, when that target isn't on the DOM. But that's more speculation than the result of testing.

**Comment by tomersela** [comment]
I have the same Issue.
After analyzing the minified file I tracked the line that causes the error:
filepicker.js Line 399:
```
var run = function(data) {
>>>        var callerId = data.id;
        if (storage.hasOwnProperty(callerId)) {
            var handlers = storage[callerId];
            for (var i = 0; i < handlers.length; i++) {
                handlers[i](data);
            }
            return true;
        }
```
Any solutions?

**Comment by zachsnow** [comment]
We are seeing the same error, over and over (several times a minute), from just a few machines (all running Chrome 51). Perhaps the user is running a plugin?

In any event, being more defensive as to the content of the message would solve the issue.

**Comment by louis49** [comment]
Still existing

**Comment by szwacz** [comment]
We've published v2.4.14 which tries to solve this issue. Please tell us if it indeed solved it.

**Comment by zachsnow** [comment]
Thanks @szwacz! We'll give it a whirl.

**Comment by rattrayalex** [comment]
I think this looks mostly-resolved for us after the fix, but still getting one such error: 

```
TypeError: Cannot read property 'id' of null
1
File https://api.filepicker.io/v2/filepicker.js line 1 col 3830 in Object.n
2
File https://api.filepicker.io/v2/filepicker.js line 1 col 215 in Object.function.r.isClass.n.(anonymous function) [as run]
3
File https://api.filepicker.io/v2/filepicker.js line 1 col 1115 in o
4
File https://d37gvrvc0wt4s1.cloudfront.net/js/v1.8/rollbar.min.js line 1 col 12717 in e._wrapped
5
File https://hired.com/interview_requests/198927 line 95 col 11096 in nrWrapper
```

**Comment by zachsnow** [comment]
Any chance you'd backport this to `v1`?

**Comment by szwacz** [comment]
@zachsnow unfortunately development of `v1` is frozen, so I can't fulfill your request.
